server:
    port: 8080
    # servlet:
    #     context-path: /${spring.application.api-version}
    
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/accountsdb
        username: root
        password: root

    jpa:
        show-sql: true
    
    sql:
        init:
            mode: always

    application:
        name: accounts

    profiles:
        active: 
            - prod
    
    config:
        import: optional:configserver:http://localhost:8071  #optional -> start the microservice even if the configserver is down, configserver-> it will always be mentioned to indicate that this is url of config server even if the name of configserver was something else even then here configserver will be mentioned it is not releted to name of config server in any way, http://localhost:8071 -> url of the configserver 
        

management:
    endpoints:
        web:
            exposure:
                include: "*"