server:
    port: 8090

spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: afshan
        password: ''
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true 

    application:
        name: loans

    config:
        import:
            - "application_prod.yml"
            - "application_qa.yml"

    profiles:
        active: 
            - "qa"

build:
    version: "0.3"

loans: # prefix for configuration
    message: "Welcome to EazyBank loans related local APIs"
    contactDetails:
        name: "Jane Doe - Developer"
        email: "jahndoe@eazybank.com"
    onCallSupport:
        - (555) 555-1633
        - (555) 555-1744
