services:
    rabbit:
        image: rabbitmq:3.13-management
        hostname: rabbitmq
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity 
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        extends:
            file: common-config.yml
            service: network-deploy-service
            
    configserver:
        image: "afshan2001/configserver:s6"
        container_name: configserver-ms
        ports:
            - "8071:8071"
        depends_on:
            rabbit:
                condition: service_healthy
        healthcheck:
            test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || (echo \"Bash failed to start config server\" && exit 1)"
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        extends:
            file: common-config.yml
            service: microservice-base-config
        environment:
            GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}

    accounts:
        image: "afshan2001/accounts:s6"
        container_name: accounts-ms
        ports:
            - "8080:8080"
        depends_on:
            configserver:
                condition: service_healthy
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            - SPRING_APPLICATION_NAME=accounts
    
    loans:
        image: "afshan2001/loans:s6"
        container_name: loans-ms
        ports:
            - "8090:8090"
        depends_on:
            configserver:
                condition: service_healthy
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            - SPRING_APPLICATION_NAME=loans

    cards:
        image: "afshan2001/cards:s6"
        container_name: cards-ms
        ports:
            - "9000:9000"
        depends_on:
            configserver:
                condition: service_healthy
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            - SPRING_APPLICATION_NAME=cards

networks:
    eazybank:
        driver: bridge