services:
    accountsdb:
        container_name: accountsdb
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: accountsdb
        extends:
            file: common-config.yml
            service: microservice-db-config

    loansdb:
        container_name: loansdb
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: loansdb
        extends:
            file: common-config.yml
            service: microservice-db-config

    cardsdb:
        container_name: cardsdb
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: cardsdb
        extends:
            file: common-config.yml
            service: microservice-db-config

            
    configserver:
        image: "afshan2001/configserver:s7"
        container_name: configserver-ms
        ports:
            - "8071:8071"
        healthcheck:
            test: "curl --fail --silent http://localhost:8071/accounts/default | grep propertySources || (echo \"Bash failed to start config server\" && exit 1)"
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        extends:
            file: common-config.yml
            service: microservice-base-config
        environment:
            GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}

    accounts:
        image: "afshan2001/accounts:s7"
        container_name: accounts-ms
        ports:
            - "8080:8080"
        depends_on:
            configserver:
                condition: service_healthy
            accountsdb:
                condition: service_healthy
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            - SPRING_APPLICATION_NAME=accounts
            - SPRING_DATASOURCE_URL=jdbc:mysql://accountsdb:3306/accountsdb
    
    loans:
        image: "afshan2001/loans:s7"
        container_name: loans-ms
        ports:
            - "8090:8090"
        depends_on:
            configserver:
                condition: service_healthy
            loansdb:
                condition: service_healthy
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            - SPRING_APPLICATION_NAME=loans
            - SPRING_DATASOURCE_URL=jdbc:mysql://loansdb:3306/loansdb

    cards:
        image: "afshan2001/cards:s7"
        container_name: cards-ms
        ports:
            - "9000:9000"
        depends_on:
            configserver:
                condition: service_healthy
            cardsdb:
                condition: service_healthy
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            - SPRING_APPLICATION_NAME=cards
            - SPRING_DATASOURCE_URL=jdbc:mysql://cardsdb:3306/cardsdb

networks:
    eazybank:
        driver: bridge