services:
    accountsdb:
        container_name: accountsdb
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: accountsdb
        extends:
            file: common-config.yml
            service: microservice-db-config

    loansdb:
        container_name: loansdb
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: loansdb
        extends:
            file: common-config.yml
            service: microservice-db-config

    cardsdb:
        container_name: cardsdb
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: cardsdb
        extends:
            file: common-config.yml
            service: microservice-db-config

            
    configserver:
        image: "afshan2001/configserver:s9"
        container_name: configserver-ms
        ports:
            - "8071:8071"
        healthcheck:
            test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || (echo \"Bash failed to start config server\" && exit 1)"
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        extends:
            file: common-config.yml
            service: microservice-base-config
        environment:
            GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}

    eurekaserver:
        image: "afshan2001/eurekaserver:s9"
        container_name: eurekaserver-ms
        ports:
            - "8070:8070"
        healthcheck:
            test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || (echo \"Bash failed to start config server\" && exit 1)"
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            - SPRING_APPLICATION_NAME=eurekaserver # with this name we have file in config server

    accounts:
        image: "afshan2001/accounts:s9"
        container_name: accounts-ms
        ports:
            - "8080:8080"
        healthcheck:
            test: "curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || (echo \"Bash failed to start config server\" && exit 1)"
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s        
        depends_on:
            accountsdb:
                condition: service_healthy
        extends:
            file: common-config.yml
            service: microservice-eurekaserver-config
        environment:
            - SPRING_APPLICATION_NAME=accounts
            - SPRING_DATASOURCE_URL=jdbc:mysql://accountsdb:3306/accountsdb
    
    loans:
        image: "afshan2001/loans:s9"
        container_name: loans-ms
        ports:
            - "8090:8090"
        depends_on:
            loansdb:
                condition: service_healthy
        healthcheck:
            test: "curl --fail --silent http://localhost:8090/actuator/health/readiness | grep UP || (echo \"Bash failed to start config server\" && exit 1)"
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        extends:
            file: common-config.yml
            service: microservice-eurekaserver-config
        environment:
            - SPRING_APPLICATION_NAME=loans
            - SPRING_DATASOURCE_URL=jdbc:mysql://loansdb:3306/loansdb

    cards:
        image: "afshan2001/cards:s9"
        container_name: cards-ms
        ports:
            - "9000:9000"
        healthcheck:
            test: "curl --fail --silent http://localhost:9000/actuator/health/readiness | grep UP || (echo \"Bash failed to start config server\" && exit 1)"
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        depends_on:
            cardsdb:
                condition: service_healthy
        extends:
            file: common-config.yml
            service: microservice-eurekaserver-config
        environment:
            - SPRING_APPLICATION_NAME=cards
            - SPRING_DATASOURCE_URL=jdbc:mysql://cardsdb:3306/cardsdb
    
    gatewayserver:
        image: "afshan2001/gatewayserver:s9"
        container_name: gatewayserver-ms
        ports:
            - "8072:8072"
        depends_on:
            accounts:
                condition: service_healthy
            loans:
                condition: service_healthy
            cards:
                condition: service_healthy
        extends:
            file: common-config.yml
            service: microservice-eurekaserver-config
        environment:
            - SPRING_APPLICATION_NAME=gatewayserver

 
networks:
    eazybank:
        driver: bridge