services:
    network-deploy-service:
        networks:
            - eazybank
    
    microservice-db-config:
        image: mysql:8.0.30
        extends:
            service: network-deploy-service
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 30s
        environment:
            MYSQL_ROOT_PASSWORD: root

    
    microservice-base-config:
        extends:
            service: network-deploy-service
        deploy:
            resources:
                limits:
                    memory: 700M

    microservice-configserver-config:
        extends:
            service: microservice-base-config
        depends_on:
            configserver:
                condition: service_healthy
        environment:
            SPRING_PROFILES_ACTIVE: prod
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/


    microservice-eurekaserver-config:
        extends:
            service: microservice-configserver-config
        depends_on:
            eurekaserver:
                condition: service_healthy
        environment:
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
