services:
    network-deploy-service:
        networks:
            - eazybank
    
    microservice-base-config:
        extends:
            service: network-deploy-service
        deploy:
            resources:
                limits:
                    memory: 700M
        environment:
            SPRING_RABBITMQ_HOST: "rabbit" # it is due to issue that rabbitmq is not able to connect to the rabbitmq 


    microservice-configserver-config:
        extends:
            service: microservice-base-config
        environment:
            SPRING_PROFILES_ACTIVE: qa
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
