server:
    port: 8080
    # servlet:
    #     context-path: /${spring.application.api-version}
    
spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: afshan
        password: ''

    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true

    application:
        name: accounts
    config:
        import:
            - "application_qa.yml"
            - "application_prod.yml"
    profiles:
        active: 
            - "qa"


build:
    version: "3.0"

accounts: # prefix for configuration
    message: "Welcome to EazyBank accounts related local APIs"
    contactDetails:
        name: "John Doe - Developer"
        email: "john@eazybank.com"
    onCallSupport:
        - (555) 555-1234
        - (555) 555-1345
     
# logging:
#   level:
#     web: DEBUG