server:
    port: 9000

spring:
    datasource:
        url: jdbc:mysql://localhost:3308/cardsdb
        username: root
        password: root

    jpa:
        show-sql: true

    sql:
        init:
            mode: always

    application:
        name: cards
    
    profiles:
        active: 
            - prod

    config:
        import: optional:configserver:http://localhost:8071 # see comments in accounts/src/main/resources/application.yml

management:
    endpoints:
        web:
            exposure:
                include: "*"