server:
    port: 9000

spring:
    datasource:
        url: jdbc:mysql://localhost:3308/cardsdb
        username: root
        password: root

    jpa:
        show-sql: true

    sql:
        init:
            mode: always

    application:
        name: cards
    
    profiles:
        active: 
            - prod

    config:
        import: optional:configserver:http://localhost:8071 # see comments in accounts/src/main/resources/application.yml

eureka:
    instance:
        prefer-ip-address: true # use ip address instead of hostname
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8070/eureka/

management:
    endpoints:
        web:
            exposure:
                include: "*"
        jmx:
            exposure:
                include:
                    - shutdown # to enable the shutdown
    health:
        readinessstate:
            enabled: true
        livenessstate:
            enabled: true
            
    endpoint:
        shutdown:
            enabled: true # to enable the shutdown endpoint in actuator
        health:
            probes:
                enabled: true
        
    info:
        env:
            enabled: true # to show the environment details in the info endpoint
    


# endpoints:
#     shutdown:
#         enabled: true # to enable the shutdown endpoint in actuator

info:
    app:
        name: Cards
        description: Cards Microservice
        version: 1.0.0

logging:
    level:
        com:
            redoca2k:
                cards: DEBUG
